lib/spotify_controller_v2_web/router.ex
defmodule SpotifyControllerV2Web.Router do
  use SpotifyControllerV2Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SpotifyControllerV2Web do
    pipe_through :browser

    get "/", PageController, :index
    get "/auth", AuthController, :index
    get "/authredirect", AuthRedirectController, :index
    get "/menu", MenuController, :index
    get "/waitForAuth", WaitForAuthController, :index
    get "/search", SearchController, :index
    post "/search", SearchController, :search
    post "/api", ApiController, :addSong
    get "/queue", QueueController, :index
    get "/artist", ArtistController, :index
    get "/album", AlbumController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SpotifyControllerV2Web do
  #   pipe_through :api
  # end
end

lib/spotify_controller_v2_web/controllers/search_controller.ex
defmodule SpotifyControllerV2Web.SearchController do
  use SpotifyControllerV2Web, :controller

  def index(conn, _params) do
    cond do
    SpotifyControllerV2.AuthManager.is_authed? ->
      render(conn, "index.html")
    conn.port == 443 and conn.remote_ip == {127,0,0,1} -> 
      redirect(conn, to: "/auth")
    true ->
      redirect(conn, to: "/waitForAuth")
    end
  end

  def search(conn, params) do
    queryString = params["searchParams"]["queryString"]
    %{songs: songs, artists: artists, albums: albums} = SpotifyControllerV2.SpotifyApiHelper.getSearchResults(queryString)
    render(conn, "searchResults.html", [query: queryString, results: songs])
  end

end

lib/spotify_controller_v2_web/views/search_view.ex
defmodule SpotifyControllerV2Web.SearchView do
  use SpotifyControllerV2Web, :view
end

lib/spotify_controller_v2_web/templates/search/index.html.eex
<%= form_for @conn, Routes.search_path(@conn, :search), [as: :searchParams], fn f -> %>
  <%= text_input f, :queryString %>
  <%= submit "Search" %>
<% end %>

lib/spotify_controller_v2_web/templates/search/searchResults.html.eex
<%= form_for @conn, Routes.search_path(@conn, :search), [as: :searchParams], fn f -> %>
  <%= text_input f, :queryString, value: @query %>
  <%= submit "Search" %>
<% end %>

<%= SpotifyControllerV2.SongTableRenderer.renderSongTable(@conn, @results, "songTableCell", true) %>